SOURCE_VALIDATION_QUEUE = "source_validation"
TELEGRAM_COLLECTION_QUEUE = "telegram_collection"
MESSAGE_PROCESSING_QUEUE = "message_processing"
CLASSIFICATION_QUEUE = "classification"
DUPLICATE_DETECTION_QUEUE = "duplicate_detection"
NOTIFICATIONS_QUEUE = "notifications"
MAINTENANCE_QUEUE = "maintenance"

TASK_QUEUES = (
    SOURCE_VALIDATION_QUEUE,
    TELEGRAM_COLLECTION_QUEUE,
    MESSAGE_PROCESSING_QUEUE,
    CLASSIFICATION_QUEUE,
    DUPLICATE_DETECTION_QUEUE,
    NOTIFICATIONS_QUEUE,
    MAINTENANCE_QUEUE,
)
